name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting du code Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installer Flake8
        run: pip install flake8

      - name: Vérifier la qualité du code
        run: flake8 backend/

  docker-build:
    name: Build & Test des conteneurs Docker
    runs-on: ubuntu-latest
    needs: lint  # Exécute seulement si Linting OK

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Construire les images Docker
        run: docker-compose build

      - name: Démarrer les services en arrière-plan
        run: docker-compose up -d

      - name: Vérifier que les services tournent
        run: docker ps

      - name: Tester User API via Nginx
        run: curl -X GET http://localhost/users || exit 1

      - name: Tester Admin API via Nginx
        run: curl -X GET http://localhost/admin || exit 1

      - name: Arrêter les conteneurs après tests
        run: docker-compose down
